fakefacts/blueprints/page/views.py
from flask import Blueprint, render_template
from flask_jwt_extended import jwt_optional

page = Blueprint('page', __name__, template_folder='templates')


@page.route('/')
@jwt_optional
def home():
    return render_template('page/home.html')

fakefacts/blueprints/user/views.py
from flask import Blueprint, render_template
from flask_jwt_extended import jwt_required

user = Blueprint('user', __name__, template_folder='templates')


@user.route('/login')
def login():
    return render_template('user/login.html')


@user.route('/signup')
def signup():
    return render_template('user/signup.html')


@user.route('/community')
@jwt_required
def community():
    return render_template('user/community.html')

fakefacts/templates/layouts/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description"
          content="{% block meta_description %}{% endblock %}">

    <title>{% block title %}{% endblock %}</title>

    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='styles/vendor/bootstrap.min.css') }}">
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='styles/main.css') }}">

    <script src="https://code.jquery.com/jquery-1.12.2.min.js"
            integrity="sha256-lZFHibXzMHo3GGeehn1hudTAP3Sc0uKXBXAzHX1sjtk="
            crossorigin="anonymous"></script>

    <script src="https://js.pusher.com/4.1/pusher.min.js"
            id="script-pusher"
            data-key="{{ config.PUSHER_KEY }}"
            data-auth-endpoint="{{ url_for('AuthView:pusher') }}"
            data-cluster="{{ config.PUSHER_CLUSTER }}"
            data-encrypted="{{ config.PUSHER_SSL }}"></script>
  </head>
  <body>
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed"
                  data-toggle="collapse" data-target="#navbar"
                  aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a href="{{ url_for('page.home') }}">
            <img src="{{ url_for('static', filename='images/fake-facts.jpg') }}"
                 class="img-responsive"
                 width="229" height="50" title="Fake Facts" alt="Fake Facts"/>
          </a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav navbar-right">
            <li class="nav-noauth">
              <a id="signup-link" href="{{ url_for('user.signup') }}" data-next="{{ url_for('user.login') }}">
                <strong>Join for FREE</strong>
              </a>
            </li>
            <li class="nav-noauth">
              <a id="login-link" href="{{ url_for('user.login') }}" data-next="{{ url_for('facts.index') }}">Login</a>
            </li>
            <li class="nav-withauth">
              <a href="{{ url_for('facts.index', username=current_user.username) }}">
                <strong>Facts</strong>
              </a>
            </li>
            <li class="nav-withauth">
              <a href="{{ url_for('user.community') }}">
                <strong>Community</strong>
              </a>
            </li>
            <li class="nav-withauth">
              <a id="logout-link" href="{{ url_for('AuthView:delete') }}" data-next="{{ url_for('page.home') }}">
                Logout
              </a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <main class="container">
      <div class="md-margin-top"></div>
      {% block body %}{% endblock %}
    </main>

    <footer class="footer text-center">
      <div class="container">
        <ul class="list-inline">
          <li class="text-muted">
            Fake Facts &copy; 2019 by
            <a href="https://ganesh-santhanam.github.io">Ganesh Santhanam</a>
          </li>
        </ul>
      </div>
    </footer>

    <script
      src="{{ url_for('static', filename='scripts/vendor/bootstrap.min.js') }}">
    </script>

    <script
      src="{{ url_for('static', filename='scripts/vendor/moment.min.js') }}">
    </script>

    <script
      src="{{ url_for('static', filename='scripts/main.js') }}">
    </script>
  </body>
</html>